project:
  type: website
  output-dir: docs

website:
  title: "The Cognition Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tbath18
      - icon: linkedin
        href: https://www.linkedin.com/in/tarunbathini/
format:
  html:
    theme: zephyr
    css: styles.css

editor: visual

